### ISSUE TITLE
License

### ISSUE THREAD

**Issue by m-yosefpor** [eygilbert/CheckerBoard#3]
I don't see the code to be under any certain license. Am I free to use the code as I will? (or at least under the terms of MIT license)

**Comment by eygilbert** [comment]
To build checkerboard you need to install Microsoft Visual Studio 2019.
There is a checkerboard solution file that contains projects for
checkerboard and several other auxiliary programs. The Community version of
VS2019 is free. If you are familiar with compiling C++ projects then that
should be enough info to get you going.

> I don't see the code to be under any certain license. Am I free to use the
> code as I will? (or at least under the terms of MIT license)
>
The code was made publicly available by the author, Martin Fierz. AFAIK he
did not distribute any licensing info with it. If you are planning to use
it for more than just personal use, I suggest that you contact him and ask
him about it. From the FAQ at his web site, "I've changed the feedback
email address to *nospam1 at fierz dot ch*."

-- Ed

**Comment by eygilbert** [comment]
I forgot to mention, in addition to the default VS2019 C++ install, you also need to install the component "C++ MFC for v142 build tools (x86 & x64)".
